name: yunyin
handle:
- rewrite: if(!is_dir() && !is_file() && path~"^(.*)$") goto "api.php/$1"

- hostaccess: if(path == "/backup.php") allow "10.0.0.0/8"
- hostaccess: if (%{REQUEST_URI} ~*"/conf/") allow "0.0"
- hostaccess: if (%{REQUEST_URI} ~*"/app/")  allow "0.0"
- hostaccess: if (path ~*"/.htacesss")  allow "0.0"

cron:
- description: backup
  url: /backup.php
  schedule: every day of month 04:32
  timezone: Beijing
