<!DOCTYPE html>
<html>
<head>
	<title>云印API接口</title>
	<meta charset="utf-8">
	<meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no"/>
	<style type="text/css">
	html {
	margin:0;
	height:100%;
	width:100%
}
body {
	background-color:#57c3ea;
	color:#EEE;
	text-align:center;
	position:relative;
	overflow-x:hidden;
	width:100%;
	min-height:98%
}
h1,h2 {
	color:#FFF;
	white-space:nowrap
}
h3,h4,h5,h6 {
	color:#fefefe
}
a {
	text-decoration:none
}
.input:active,.input:hover,.input:focus {
	color:#57c3ea;
	font-weight:bolder;
	background:#fefefe
}
.input[disabled] {
	cursor:wait
}
#img,.input {
	padding:10px 15px 5px 15px;
	width:75%;
	margin-top:1%;
	margin-bottom:2%;
	font-family:Lato,Helvetica,Arial,sans-serif;
	font-size:1.5em;
	line-height:1.8em;
	background-color:transparent;
	color:#FFF;
	border:4px solid #fefefe;
	border-radius:6px;
	box-shadow:none;
	-webkit-transition:border .25s linear,color .25s linear,background-color .25s linear;
	transition:border .25s linear,color .25s linear,background-color .25s linear
}
#img,.code {
	width:36%;
	padding:1px;
	max-height: 2.5em;
	vertical-align:middle;
	display:inline-block
}
#codeArea {
	height:80px;
	display:none
}
#img {
	margin-right:1%;
	border:0
}
.code {
	margin-left:1%;
	padding-left:10px
}
#tip {
	color:#ec7329;
	font-size:larger;
	font-weight:bolder;
	text-decoration:underline
}
#<?=isset($reg)?'auth':'reg'?>form {
	display:none
}
	</style>
</head>
<body>
 <h1>云印API登录</h1>
  <div id="tip">
   <?=isset($msg) ? $msg : ''?>
  </div>
  <form id="authform" method="post" onsubmit="return checkform();">
  	<p>
  		<a href="http://print.yunyin.org/#/forget">忘记密码？</a>
  	</p>
   <input name="name" type="text" class="input" placeholder="学号" id="number" onchange="checknumber()" required="" />
   <input name="password" type="password" class="input" placeholder="密码" id="password" required="" />
   <div id="codeArea">
    <img id="img" src="" />
    <input name="code" type="text'" class="code input" placeholder="验证码" id="code" />
   </div>
   <button class="input" type="submit" id="submit">验证</button>
  </form>
  <form id="regform" method="post" action="/api/register" onsubmit="return checkreg();">
   <h6>第一次使用云印？我们推荐您设置独立的密码,这样更加安全！<br />如果您跳过设置,将会使用验证密码作为云印密码!</h6>
   <input name="password" type="password" class="input" placeholder="新的密码" id="reg_password" required="" />
   <input type="password" class="input" placeholder="确认密码" id="repassword" onblur="checkreg()" required="" />
   <button class="input code" type="submit" id="reg">设置密码</button>
   <a class="input code" href="/api/register">跳过设置</a>
  </form>
<script>
function ajax(method, url, data, callback) {
	var xhr = new XMLHttpRequest();
	xhr.open(method, url, true);
	xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded;charset=utf-8');
	xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
	xhr.send(data);
	xhr.onreadystatechange = function() {
		if (xhr.readyState == 4) {
			if (xhr.status == 200) {
				var data = JSON.parse(xhr.responseText);
				callback(data);
			} else {
				showtips("网路异常");
			}
		}
	};
}

function showtips(msg) {
	var tip = document.getElementById('tip');
	tip.innerHTML = msg;
	tip.style.display = '';
}

function getVerifyCode(sch_id) {
	var img = document.querySelector('#img');
	var verifyCodeCallback = function(data) {
		if (data.status == 1) {
			document.querySelector('#codeArea').style.display = 'block';
			document.querySelector('#code').setAttribute('required', 'required');
			img.setAttribute('src', data.info['img']);
			img.onclick = function(){getVerifyCode(sch_id);};
		}
	}
	img.onclick=null;
	ajax('GET', '/school/' + sch_id + '/code', '', verifyCodeCallback);
}

function showSchoolInfo(sch_id) {
	ajax('GET', '/school/' + sch_id, '', function(data) {
		if (data.status == 1) {
			var school = data.info;
			showtips(school['name'] + ':首次登录用<a target="_blank" href="' + school['verifyurl'] + '">' + school['verify'] + '</a>密码验证');
		}
	});
}
var checknumberCallback = function(data) {
	if (data.status) {
		document.getElementById('codeArea').style.display = 'none';
		document.getElementById('code').removeAttribute('required');
		showtips('');
		var info = data.info;
		for (var s in info) {
			if (info[s] != 0) {
				getVerifyCode(s);
				showSchoolInfo(s);
			}
		};
	} else {
		showtips("学号好像不是所支持的学校，请检查一下学号^_^");
		return false;
	}
}

function checknumber() {
	var number = document.getElementById('number').value.trim();
	var reg = /^(\d{6,7})|(\d{10})$/;
	if (!reg.test(number)) {
		showtips("学号格式不对哦，请检查一下学号^_^");
		document.getElementById("number").focus();
		return false;
	} else {
		showtips('');
	}
	ajax('POST', '/school/number', 'number=' + number, checknumberCallback);
}
var authCallback = function(data) {
	switch (data.status) {
		case 1: //登录成功
			showtips('');
			location.reload();
			break;
		case 2: //注册
			document.querySelectorAll('h1').textContent = '设置云印密码';
			document.getElementById('authform').style.display = 'none';
			document.getElementById('regform').style.display = '';
			showtips('');
			break;
		case 0:
		case -1:
			showtips(data.info);
			enable();
			break;
		default:
			enable();
			showtips('请求异常');
	}
};

function enable() {
	document.getElementById('authform').removeAttribute('disabled');
	document.getElementById('number').removeAttribute('disabled');
	document.getElementById('password').removeAttribute('disabled');
	document.getElementById('code').removeAttribute('disabled');
	var submit = document.getElementById('submit');
	submit.textContent = '验证';
	submit.removeAttribute('disabled');
}

function checkform() {
	document.getElementById('authform').setAttribute('disabled', 'disabled');
	var submit = document.getElementById('submit');
	submit.textContent = '验证中';
	submit.setAttribute('disabled', 'disabled');
	checknumber();
	var number= document.getElementById('number').value.trim();
	var password = document.getElementById('password').value.trim();
	var code = document.getElementById('code').value.trim();
	var data = 'number=' + number + "&password=" + password;
	if (code) {
		data += "&code=" + code;
	}
	ajax('POST', '/auth/', data, authCallback);
	return false;
}

function checkreg() {
	var password = document.getElementById('reg_password').value;
	var repassword = document.getElementById('repassword').value;
	if (password.trim() == repassword.trim()) {
		document.getElementById('reg_password').value = password.trim();
		showtips('');
		return true;
	} else {
		showtips('两次密码不一样');
		return false;
	}
}
</script>
</body>
</html>