<html>
	<head>
		<meta charset="utf-8">
		<title>云印服务</title>
		<style type="text/css">
		body{color: #FEFEFE;background: #00A6E9;text-align: center;}
		div{width:80%;color: #4DBEF0;background:#FFF;margin: 10%;}
		h4{color: #34495F}
		a{color: #99d1f8}
		</style>
	</head>
	<body>
		<h1>云印服务接口</h1>
		<hr>
		<div><br>
		<h3>新版接口</h3>
		<hr>
		<h4>详情查看文档</h4>
		<br>
		</div>
		<h2><a href="https://github.com/YunYinORG/YunYinService/wiki">文档</a></h2>
		<img src="//www.yunyin.org/assets/image/logo.png">
	</body>
</html>
